### PR TITLE
Add hikey960

### PR DESCRIPTION
**Pull request by photoszzt**

### CODE REVIEW

**Comment by photoszzt** [comment]
@lhelontra review?

**Comment by lhelontra** [comment]
Hi, thanks for comtribuition. Removes the dockerfile, just hikey config only.

**Comment by photoszzt** [comment]
Done.

**Comment by lhelontra** [comment]
Changes the variable TF_VERSION="v1.11.0" and rename file to hikey960.conf,  keeping config filenames format.

**Comment by photoszzt** [comment]
Done.

**Comment by lhelontra** [comment]
Thanks

**Pull request merged**
